### ISSUE TITLE
Facebook in development mode

### ISSUE THREAD

**Issue by dillingham** [joelbutcher/jetstream-demo#1]
Got this screen when attempting to login, you might not see if by being the author.

<img width="516" alt="Screen Shot 2020-11-22 at 1 31 09 AM" src="https://user-images.githubusercontent.com/29180903/99896859-6eaa3e00-2c62-11eb-98be-c2971fa3ba22.png">

**Comment by joelbutcher** [comment]
@dillingham I'll add you as a test user later and use your GitHub email 👍

**Comment by dillingham** [comment]
Cool thanks, just wasn't sure if you wanted to publish it for demo for others.

**Comment by joelbutcher** [comment]
@dillingham I need an official privacy policy for Facebook, so I've removed them - I'll add other providers though
