### ISSUE TITLE
500 error after register/login via GitHub

### ISSUE THREAD

**Issue by Silver343** [joelbutcher/jetstream-demo#2]
Currently getting a 500 server error on redirect after register via GitHub, after login via GitHub and after clicking cancel on the authorize application page.

**Comment by joelbutcher** [comment]
@Silver343 Thanks for the spot - I've just pushed up a fix for this [here](https://github.com/laravel/jetstream/pull/444/commits/424e9651e98637119668e819011c590b24bed170).

The resulting code should be live on the demo site now.
